### ISSUE TITLE
Icons render as comments ☹🤔

### ISSUE THREAD

**Issue by piscopancer** [qwikest/icons#10]
`v 0.0.7`

Hi, is it just for me or for you too that icons are not rendered? they are commented out as if Qwik refuses to render them. What can it be? 🙄 

### Code
![image](https://user-images.githubusercontent.com/109352196/236647527-4fa91ee5-b76e-4c88-8c25-a53a00ed42a3.png)

### Html
![image](https://user-images.githubusercontent.com/109352196/236647556-af4bd441-f884-4c61-8237-9e81fa10830d.png)

**Comment by astraldev** [comment]
Same issue with  `qwik: 1.0.0` and the other versions of this package.... Don't really know what is going on

**Comment by da8ah** [comment]
Yup, I had the same problem here #9 using **pnpm** and **qwik 1.0.0**, but only happens with ```mode --ssr```. If you remove it from dev script in the ```package.json``` it works fine.

**Comment by NiklasPor** [comment]
Issue should be resolved in `@qwikest/icons@0.0.8`. If not please comment in issue #3

**Comment by da8ah** [comment]
v0.0.8
Yes, they are working now. Thank you so much @NiklasPor and wishing you the best of luck with all your projects!

![image](https://github.com/qwikest/icons/assets/62577449/b51b88cd-26dd-4702-a2a1-51048f7b5244)
