### ISSUE TITLE
QWIK WARN Duplicate implementations of "JSXNode" found

### ISSUE THREAD

**Issue by brandiqa** [qwikest/icons#11]
In the latest version of Qwik `1.1.1`,  and also `1.0.0`, I get the following error in the server console whenever I use qwikest icons:

```bash
QWIK WARN Duplicate implementations of "JSXNode" found
```

Older versions of Qwik have no issue though. I guess something changed with the latest implementation

**Comment by brandiqa** [comment]
Found a similar issue reported 3 weeks ago regarding using Qwik Styled Vanilla Extract. See https://github.com/BuilderIO/qwik/issues/3883

**Comment by origranot** [comment]
Same here.

**Comment by NiklasPor** [comment]
As mentioned above, this is not the only package affected from this warning. Once we have a fix which won't force me to merge all entry points into one, I'll apply that one.

#BuilderIO/qwik#3883

**Comment by josemartinez111** [comment]
Still have the same issue in version 1.1.4.

**Comment by wmertens** [comment]
It looks to be caused by imports importing qwik, they get a different instance of `qwik/core.prod.mjs`. This causes the JSXNode class to be duplicated, and some nodes won't render because of it.

**Comment by chempogonzalez** [comment]
Hi! I mentioned my temporal solution for this in order to suppress just these warnings which are very annoying.

[Temporal solution mentioned in #BuilderIO/qwik#3883](https://github.com/BuilderIO/qwik/issues/3883#issuecomment-1575046705).

Hope it helps you @josemartinez111, @origranot, @brandiqa :)

**Comment by y471n** [comment]
Facing the same issue.  How can this be prioritized? 🙏

**Comment by NiklasPor** [comment]
As far as I see this must be fixed on Qwik side: https://github.com/BuilderIO/qwik/issues/3883

**Comment by NiklasPor** [comment]
This should be fixed in >= @qwikest/icons@0.0.9. If not please comment here or write a new issue ❤️
