### ISSUE TITLE
Rebuild to get latest Icons please :)

### ISSUE THREAD

**Issue by gabrielgrant** [qwikest/icons#15]
I'm not able to import `LuDot`:

```
'"@qwikest/icons/lucide"' has no exported member named 'LuDot'. Did you mean 'LuBot'?ts(2724)
lu.d.ts(120, 22): 'LuBot' is declared here.
```

Despite the icon existing: https://lucide.dev/icons/dot

Most others I've tried (eg `LuCircleDot`) seem to work fine

```
$ npm list @qwikest/icons
my-qwik-basic-starter@ /home/gabriel/repos/x
└── @qwikest/icons@0.0.8
```

**Comment by gabrielgrant** [comment]
Looks like the issue is that this icon is in a relatively new release: https://github.com/lucide-icons/lucide/releases/tag/v0.198.0

while [this package accepts a range of versions (`"lucide-static": ">=0.115.0 <1.0.0"`)](https://github.com/qwikest/icons/blob/main/package.json#L152) seems it [hasn't been regenerated/republished in a few months](https://www.npmjs.com/package/@qwikest/icons)

@NiklasPor Would you be open to having a github action that rebuilds/republishes this package? Either just on a regular schedule, or in response to changes in upstream icon sources

To have it be in response to upstream changes, thinking that something like dependabot + an action that responds to those PRs might be the way to go? Alternatively, just a basic action run on a schedule seems like it should be pretty straightforward and probably sufficient

In the meantime, would be awesome if you could just rebuild/repush this manually!

**Comment by NiklasPor** [comment]
I'm rebuilding it right now (and hopefully fixing the SSR issues) – regular github action sounds like a good idea 👍

**Comment by NiklasPor** [comment]
@gabrielgrant `0.0.10` is available and includes `LuDot` 👍 For a generic automated solution, I'd say we stay easy and just let it run once a week and only publish something, when something changed. Also bear in mind that not all icons are fetched via `npm`, the majority comes from URLs via Github 😁

**Comment by NiklasPor** [comment]
I'll close this issue for now, if anything ever comes up again, feel free to create a new issue 👍
