### ISSUE TITLE
Add Icon Pack: flowbite

### ISSUE THREAD

**Issue by PatrickJS** [qwikest/icons#16]
https://flowbite.com/icons/

**Comment by NiklasPor** [comment]
Awesome, this looks simple to integrate 👍

**Comment by NiklasPor** [comment]
This is available in `0.0.12`, thanks for the issue.

Just as a disclaimer, the icon names seem quite inconsistent:
https://github.com/themesberg/flowbite-icons/pull/14
https://github.com/themesberg/flowbite-icons/pull/13
