### ISSUE TITLE
QWIK WARN Duplicate implementations of "JSXNode" found

### ISSUE THREAD

**Issue by kepi** [qwikest/icons#18]
Hi,

I'm getting 3x `QWIK WARN Duplicate implementations of "JSXNode" found` warning for every icon I use. I'm on @qwikest/icons 0.0.13 and qwik 1.3.2.

What seems different from #11 if I understood it correctly is, that I'm getting this error during development.

**Comment by NiklasPor** [comment]
I can try bumping the dependencies and build to the latest version, that might fix it (again 👀)

**Comment by kepi** [comment]
Thanks for fast reply, but I just found out that problem is probably somewhere in my stack. I have same trouble with @unpic/qwik.

I'm using Nx but when I start qwik without Nx, it works. It hadn't cross my mind before that it might be the root of issue. Maybe something in Qwik-Nx executor... I'm checking it but wanted to let you know quickly so you don't spend time on this. Thanks!

**Comment by kepi** [comment]
For sake of those who bump into same problem and using Nx, replacing `@nx/vite` with simple command did the job in my case:

```
    "serve": {
      "executor": "nx:run-commands",
      "options": {
        "command": "vite --mode=ssr",
        "cwd": "apps/porici"
      }
    },
```

@NiklasPor sorry for taking your time. I tried so many thing before reporting :D

**Comment by ertl** [comment]
@kepi I have the same problem. Can you explain what exactly the problem is here? Your configuration seems to fix the warning, but then I get errors when loading modules in combination with @modular-forms/qwik.

**Comment by kepi** [comment]
Sorry, I moved away from Nx and don't remember this exactly.

In my case Nx helped with couple things but complicated more. There is too much boilerplate, hidden traps and magic.

**Comment by ertl** [comment]
@kepi no problem.

I solved the warning by switching to a single version policy for my dependency management (https://nx.dev/concepts/more-concepts/dependency-management). Now also the `@nx/vite` executor works fine.
