### ISSUE TITLE
Request - Add Tabler icons

### ISSUE THREAD

**Issue by absolutejam** [qwikest/icons#2]
First of all, thanks for creating this package!

The docs say to create issue for any requests, so I thought I'd suggest Tabler icons as it's one I use pretty heavily.

If you have any pointers on cloning & testing this locally, I'd be happy to give it a shot my self.

Regards,
James.

**Comment by NiklasPor** [comment]
3400 icons is a lot 😄 I'll add it this in this evening, should be a matter of minutes. I'll link you the commit afterwards, then you can create a PR if you need any other lib the next time 👍

**Comment by NiklasPor** [comment]
Tabler Icons were added in `0.0.5` 👍
