### ISSUE TITLE
I get QWIK WARN Duplicate implementations of "JSXNode" found with mode --ssr & blank page without it. (WSL)

### ISSUE THREAD

**Issue by da8ah** [qwikest/icons#9]
Hi, can anyone help please?

Package Manager
npm & pnpm

Qwik Version
1.0.0
0.107.0
0.104.0

Operating System (or Browser)
WSL/MS Edge

Node Version (if applicable)
18.15.0

Which component is affected?
Qwik Runtime

Expected Behaviour
To render Icons in any component from the qwik template with the snippet provided when using ```pnpm dev``` or ```npm run dev```. I tried with mode --ssr & without it.

Actual Behaviour
When using mode --ssr displays in VSCode console two times: QWIK WARN Duplicate implementations of "JSXNode" found
Whitout mode --ssr displays in the browser only a blank page, but I still get the title and the icon for the head of the HTML

**Comment by NiklasPor** [comment]
This should be fixed with version `0.0.7` I just released. If not please reopen the issue 👍

**Comment by da8ah** [comment]
Thanks a lot. It's working partially.

Test it with:
pnpm
Qwik v1.0.0
Icons v0.0.7

It's working without ```mode --ssr``` but using it doesn't work yet. It shows the same two logs of "QWIK WARN Duplicate implementations of "JSXNode" found" and the icon isn't rendering.
